dist: xenial
language: java
jdk: 
  - openjdk11
addons:
  sonarcloud:
    organization: "thiagoveloso" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Pcoverage -Dsonar.projectKey=thiagovp_spring-cloud-netflix