version: '3.1'
services:
  database-crud:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'microservices'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'microservices123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes: 
      - db-crud:/var/lib/mysql
  database-pagamento:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'pagamento'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'microservices'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'microservices123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes: 
      - db-pagamento:/var/lib/mysql
  database-auth:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'auth'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'microservices'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'microservices123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes: 
      - db-auth:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
volumes:
  rabbitmq:
  db-crud:
  db-pagamento:
  db-auth:
  
  